package kz.law.AppCreator.botapi;

public enum BotState {
    FILLING_PROFILE,
    ASK_DESTINY,
    ASK_FULL_NAME,
    ASK_JOB_TITLE,
    ASK_PHONE_NUMBER,
    ASK_SERVICE_NAME,
    ASK_TARGET,
    ASK_AMOUNT,
    ASK_SIDE_ONE,
    ASK_SIDE_TWO,
    ASK_SIGNED_DATE,
    ASK_AGREEMENT_TYPE,
    ASK_CONDITIONAL_OBJECTS,
    ASK_SPECIAL_REQUIREMENTS,
    ASK_DEAL_AMOUNT,
    ASK_PAYMENT,
    ASK_IIN_BIN,
    ASK_ADDRESS,
    ASK_JSK_BANK,
    ASK_ADDITIONAL_INFO,
    PROFILE_FILLED
}
